#!/bin/sh

if test -z $1; then
  echo ""
else
  choice=$1
fi

while :; do

  if test -z "$choice"; then
    read -p "Rebuild: All(0), esmserver(1), checker_current_game(2), checker_leaderboard(3), checker_subscriber(4), checker_unclaim(5), gloader(6), wwwloader(7)" choice
  fi
  
  if [ "$choice" -ge 0 ] && [ "$choice" -le 99 ]; then
    break
  else
    read -p "Rebuild: All(0), esmserver(1), checker_current_game(2), checker_leaderboard(3), checker_subscriber(4), checker_unclaim(5), gloader(6), wwwloader(7)" choice
  fi

done

echo "calling remote script with choice=$choice"


SOURCE_FOLDER='./'
TARGET_FOLDER='~/esm-datastore'
PROD_SERVER='pow'
USER='ken'

rsync -av $SOURCE_FOLDER $USER@$PROD_SERVER:$TARGET_FOLDER --exclude-from='.rsyncignore'
ssh $USER@$PROD_SERVER 'bash -s' < remote_build.sh $choice

# copy back the results
rsync -av $USER@$PROD_SERVER:$TARGET_FOLDER/build ./