export JWK_URL="https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
export JWK_AUDIENCE="esports-mini"
export JWK_ISSUER="https://securetoken.google.com/esports-mini"
export DB_CERT_PATH="/usr/local/bin/CA.crt"
export DB_CONN_STRING="postgresql://doadmin:tf45h3hpz6xstby6@esm-api.aadi.my:25432/postgres?sslmode=require"
export SERVER_TIMEZONE="8"