version: "3.9"
services:

  frontenvoy:
    image: envoyproxy/envoy:v1.16.2
    volumes:
      - ./front/envoy.yaml:/etc/envoy/envoy.yaml
      - /etc/letsencrypt/live/aadi.my/fullchain.pem:/etc/envoy/fullchain.pem
      - /etc/letsencrypt/live/aadi.my/privkey.pem:/etc/envoy/privkey.pem
    networks:
      - envoymesh
    expose:
      - "443"
    ports:
      - "443:443"

  grpc-web-proxy:
    image: envoyproxy/envoy:v1.16.2
    volumes:
      - ./grpc_web_proxy/envoy.yaml:/etc/envoy/envoy.yaml
    restart: always
    environment: 
      - ENVOY_UID=0
      - ENVOY_GID=0
    networks:
      envoymesh:
        aliases:
          - grpc-web-proxy
    depends_on:
      - "esmservice"
    links:
      - "esmservice"
    expose:
      - "8080"
    ports: 
      - "8080:8080"

  esmservice:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    restart: always
    networks:
      envoymesh:
        aliases:
          - esmservice
    expose:
      - "50051"
    ports:
      - "50051:50051"

  esm-game-loader:
    build:
      context: .
      dockerfile: ./gloader/Dockerfile
    restart: always
    networks:
      envoymesh:
        aliases:
          - esm-game-loader
    expose:
      - "3033"
    ports:
      - "3033:3033"

networks:
  envoymesh: {}