version: "3.9"
services:

  frontenvoy:
    image: envoyproxy/envoy:v1.16.2
    volumes:
      - ./front/envoy.yaml:/etc/envoy/envoy.yaml
      # - /etc/letsencrypt/live/aadi.my/fullchain.pem:/etc/envoy/fullchain.pem
      # - /etc/letsencrypt/live/aadi.my/privkey.pem:/etc/envoy/privkey.pem
      - /etc/letsencrypt/live/esm-admin.aadi.my/fullchain.pem:/etc/envoy/esm-admin/fullchain.pem
      - /etc/letsencrypt/live/esm-admin.aadi.my/privkey.pem:/etc/envoy/esm-admin/privkey.pem
      - /etc/letsencrypt/live/esm-api.aadi.my/fullchain.pem:/etc/envoy/esm-api/fullchain.pem
      - /etc/letsencrypt/live/esm-api.aadi.my/privkey.pem:/etc/envoy/esm-api/privkey.pem
    restart: always
    environment: 
      - ENVOY_UID=0
      - ENVOY_GID=0
    networks:
      - envoymesh
    expose:
      #- "80"
      - "443"
    ports:
      #- "80:80"
      - "443:443"

  grpc-web-proxy:
    image: envoyproxy/envoy:v1.16.2
    volumes:
      - ./grpc_web_proxy/envoy.yaml:/etc/envoy/envoy.yaml
    restart: always
    environment: 
      - ENVOY_UID=0
      - ENVOY_GID=0
    networks:
      envoymesh:
        aliases:
          - grpc-web-proxy
    depends_on:
      - "esmservice"
    links:
      - "esmservice"
    expose:
      - "8080"
    ports: 
      - "8080:8080"

  esmservice:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    restart: always
    networks:
      envoymesh:
        aliases:
          - esmservice
    expose:
      - "50051"
    ports:
      - "50051:50051"

  esm-game-loader:
    build:
      context: .
      dockerfile: ./gloader/Dockerfile
    restart: always
    networks:
      envoymesh:
        aliases:
          - esm-game-loader
    expose:
      - "3033"
    ports:
      - "3033:3033"

  esm-admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    restart: always
    networks:
      envoymesh:
        aliases:
          - esm-admin
    expose:
      - "3030"
    ports:
      - "3030:3030"
      
  esm-stripe:
    build:
      context: .
      dockerfile: ./stripe/Dockerfile
    restart: always
    networks:
      envoymesh:
        aliases:
          - esm-stripe
    expose:
      - "4242"
    ports:
      - "4242:4242"
networks:
  envoymesh: {}