version: "3.9"
services:

  frontenvoy:
    image: envoyproxy/envoy:v1.16.2
    volumes:
      - ./front/envoy.yaml:/etc/envoy/envoy.yaml
      - /etc/letsencrypt/live/esm-api.aadi.my-0001/fullchain.pem:/etc/envoy/certs/fullchain.pem
      - /etc/letsencrypt/live/esm-api.aadi.my-0001/privkey.pem:/etc/envoy/certs/privkey.pem
    restart: always
    environment: 
      - ENVOY_UID=0
      - ENVOY_GID=0
    networks:
      - envoymesh
    expose:
      - "443"
    ports:
      - "443:443"

  grpc-web-proxy:
    image: envoyproxy/envoy:v1.16.2
    volumes:
      - ./grpc_web_proxy/envoy.yaml:/etc/envoy/envoy.yaml
    restart: always
    environment: 
      - ENVOY_UID=0
      - ENVOY_GID=0
    networks:
      - envoymesh
    depends_on:
      - "esmservice"
    links:
      - "esmservice"
    expose:
      - "8080"
    ports: 
      - "8080:8080"

  esmservice:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    restart: always
    environment:
      LISTEN_ON: 0.0.0.0:50051
      BEFORE_LOGIN_TOKEN: Bearer before-login-token
      STRIPE_SECRET: sk_test_51IOa7gBGCaV2oEVpEDw9fOn1fUn8IaPOemu7Yjkg6N75C3ahsd7sEQr3ait4JYU55wfCBbXCRPIhcUxGMVtQYA6A003YKMqkYF
      CHECKER_TIME_WAIT: 60
      FCM_KEY: AAAAzT8d8lM:APA91bHtFSHVIBiiSDUWSaUkrYNrcBSyhMY_JBYSeaaoWpkrxSgBO-7xgHtySH3qfTvsgHHTIsrh_SwwirCvTTuOWBl0--JhddEV8MFnEgWuGRPOXPVyTBHym5k9gh8WrCxr-rY13Y54
      JWK_URL: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
      JWK_AUDIENCE: esports-mini
      JWK_ISSUER: https://securetoken.google.com/esports-mini
      DB_CONN_STRING: postgresql://doadmin:tf45h3hpz6xstby6@dbpg-master:25432/postgres?sslmode=require
      SERVER_TIMEZONE: 8
    networks:
      - envoymesh
    expose:
      - "50051"
    ports:
      - "50051:50051"

  esm-game-loader:
    build:
      context: .
      dockerfile: ./gloader/Dockerfile
    restart: always
    environment:
      LISTEN_ON: 0.0.0.0:3033
      JWK_URL: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
      JWK_AUDIENCE: esports-mini
      JWK_ISSUER: https://securetoken.google.com/esports-mini
      DB_CONN_STRING: postgresql://doadmin:tf45h3hpz6xstby6@dbpg-master:25432/postgres?sslmode=require
      SERVER_TIMEZONE: 8
    networks:
      - envoymesh
    expose:
      - "3033"
    ports:
      - "3033:3033"

  esm-admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    restart: always
    environment:
      LISTEN_ON: 0.0.0.0:3030
    networks:
      - envoymesh
    expose:
      - "3030"
    ports:
      - "3030:3030"
      
  esm-stripe:
    build:
      context: .
      dockerfile: ./stripe/Dockerfile
    restart: always
    environment:
      PORT: 4242
      STRIPE_SECRET: sk_test_51IOa7gBGCaV2oEVpEDw9fOn1fUn8IaPOemu7Yjkg6N75C3ahsd7sEQr3ait4JYU55wfCBbXCRPIhcUxGMVtQYA6A003YKMqkYF
    networks:
      - envoymesh
    expose:
      - "4242"
    ports:
      - "4242:4242"


  dbpg-master:
    build:
      context: .
      dockerfile: ./postgres/master/Dockerfile
    restart: always
    command: >
      -c listen_addresses=*
      -c port=25432
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c ssl_ca_file=/var/lib/postgresql/CA.crt
      -c ssl_crl_file=/var/lib/postgresql/CA.crl
      -c hot_standby=on
      -c wal_level=replica
      -c wal_keep_size=1024
      -c max_wal_senders=10
      -c wal_compression=on
      -c archive_mode=on
      -c archive_command='cd .'
    volumes: 
      - dbpg-master-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: tf45h3hpz6xstby6
      PG_REP_USER: replicator
      PG_REP_PASSWORD: tf45h3hpz6xstby6
    networks:
      - envoymesh
    expose:
      - "25432"
    ports:
      - "25432:25432"

  dbpg-standby-01:
    build:
      context: .
      dockerfile: ./postgres/standby/Dockerfile
    restart: always
    command: gosu postgres postgres 
      -c listen_addresses=*
      -c port=25433
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c ssl_ca_file=/var/lib/postgresql/CA.crt
      -c ssl_crl_file=/var/lib/postgresql/CA.crl
      -c restore_command='cp /archives/%f %p'
      -c primary_conninfo='user=replicator password=tf45h3hpz6xstby6 channel_binding=prefer host=dbpg-master port=25432 sslmode=prefer sslcompression=0 ssl_min_protocol_version=TLSv1.2 gssencmode=prefer krbsrvname=postgres target_session_attrs=any'
    volumes: 
      - dbpg-standby-01-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: tf45h3hpz6xstby6
      PG_REP_USER: replicator
      PG_REP_PASSWORD: tf45h3hpz6xstby6
      PG_MASTER_HOST: dbpg-master
      PG_MASTER_PORT: 25432
    networks:
      - envoymesh
    expose:
      - "25433"
    ports:
      - "25433:25433"

volumes:
  dbpg-master-data:
  dbpg-standby-01-data:
networks:
  envoymesh: {}